### ISSUE TITLE
Create integration test script

### ISSUE THREAD

**Issue by fwimp** [fwimp/roz#1]
It'd be useful to have an integration test script to aid the OZ developers in ensuring that they don't break compatibility with `roz` (or at least that they know when they do).

See https://github.com/OneZoom/OZtree/issues/867
 
> Somewhat unrelated, but is there an integration test script for roz? Something where I can do ``exercise_roz_api.R https://my-local-oz.com/`` to ensure any future releases don't break the API would be very useful (feel free to move this to whichever repository is appropriate).

_Originally posted by @lentinj in https://github.com/OneZoom/OZtree/issues/867#issuecomment-2324160862_

**Comment by lentinj** [comment]
The script shouldn't get too hung up on the return values if possible, i.e. checking that ``popularity``() returns a data.frame with appropriately-typed columns, one per input OTT, rather than checking the popularity values match what you expect. As well as the data potentially changing in the future, the tree on my laptop is inevitably out-of-date and will produce different values.

In theory we have the same problem with OTTs too, but I don't think it's worth losing sleep over. Common OTTs changing would be a bigger headache than just this script, and if my laptop is missing OTTs it probably means I should get around to updating the tree.

Thanks very much :)

**Comment by fwimp** [comment]
@lentinj Added a script to do some of this checking (available at [`tools/exercise_roz_api.R`](https://github.com/fwimp/roz/blob/master/tools/exercise_roz_api.R)).

This tests the following:
## identifier2ott _(endpoint: getOTT)_
- Executed correctly
- Correct number of fields in response
- All ids are numeric

## node_images _(endpoint: node_images)_
- Executed correctly
- Correct number of rows in response
- Correct number of fields returns
- Field types are as expected

## ott2common _(endpoint: otts2vns)_
- Executed correctly
- Correct number of rows in response
- Correct number of fields returns
- Field types are as expected
- Findall executes successfully
- Findall finds the same number of rows
- Findall finds more names (fields) than non-findall

## ott2identifiers _(endpoint: otts2identifiers)_
- Executed correctly
- Correct number of rows in response
- Correct number of fields returns
- Field types are as expected

## popularity _(endpoint: popularity/list)_
- Executed correctly
- Correct number of rows in response
- Correct number of fields returns
- Field types are as expected
- Expand executes successfully
- Expand finds more names than non-expanded
- Maxtaxa reduces number of responses correctly
- Include_raw executes successfully
- Include_raw adds exactly 1 column.

---

Script usage is as follows:

```
usage: exercise_roz_api.R [-h] [-c] [-l] [-m] url

Test roz package API interactions.

positional arguments:
  url                   The base level URL of OneZoom.

optional arguments:
  -h, --help            show this help message and exit
  -c, --compat          Use compatability mode for http queries.
  -l, --local           Load local package from source using devtools.
  -m, --nosuppressmessages
                        Disable suppression of package messages.
```

Use compat mode if you are running in Linux and getting errors about ssl stuff.

My testing runs were mostly executed like this:

`RScript exercise_roz_api.R "https://onezoom.org/" -cl`

That said if you have installed `roz` then you may just need `-c` or maybe no arguments at all.
